// React/src/components/partials/Serviceresults.jsx
import { useState, useRef } from "react";
import { useEffect } from "react";
import Select from "react-select";
import { useParams, useNavigate } from "react-router-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faLocationDot,
    faSearch,
    faPhone,
} from "@fortawesome/free-solid-svg-icons";
import Footer from "./footer";
import PriceRangeFilter from "./PriceRangeFilter";
import Navbar from "./Navbar";
import axiosClient from "../../axiosClient";
import { Link } from "react-router-dom";
import { useStateContext } from "../../contexts/contextProvider";
import { decode as base64_decode, encode as base64_encode } from "base-64";
import ServiceSearch from "../partials/ServiceSearch";
import CardsPagination from "./CardsPagination";
import BackBtn from "./BackBtn";
const ServiceResults = () => {
    const categories = [
        { value: "Agriculture", label: "Agriculture" },
        { value: "Arts/Culture", label: "Arts/Culture" },
        { value: "Auto", label: "Auto" },
        {
            value: "Domestic (Home Help etc)",
            label: "Domestic (Home Help etc)",
        },
        { value: "Fashion", label: "Fashion" },
        { value: "Finance/Accounting", label: "Finance/Accounting" },
        { value: "Food", label: "Food" },
        { value: "Legal", label: "Legal" },
        { value: "Media/Internet", label: "Media/Internet" },
        { value: "Other", label: "Other" },
        { value: "Pets", label: "Pets" },
        { value: "Real Estate", label: "Real Estate" },
        { value: "Retail", label: "Retail" },
        { value: "Security", label: "Security" },
        { value: "Sports/Gaming", label: "Sports/Gaming" },
        {
            value: "Technology/Communications",
            label: "Technology/Communications",
        },
    ];

    const { resIds } = useParams();
    const { loc } = useParams();

    const [selectedCategory, setSelectedCategory] = useState(null);
    const [results, setResults] = useState("");
    const locationInputRef = useRef(null);
    const count = results.length;
    let res = [];

    const [cartRes, setCartRes] = useState("");
    var max = 1000000;
    var min = 0;

    //KEVIN
    useEffect(() => {
        const getResults = () => {
            axiosClient
                .get("/ServiceResults/" + base64_decode(resIds))
                .then(({ data }) => {
                    setResults(data.data);
                    res = data.data;
                    console.log(data);
                    var x = navigator.geolocation;
                    x.getCurrentPosition(success, failure);
                })
                .catch((err) => {
                    console.log(err);
                });
        };
        getResults();

        var slider = document.getElementById("slider");
        if (slider && slider.noUiSlider) slider.noUiSlider.destroy();

        amountSlider();
    }, []);

    const amountSlider = () => {
    noUiSlider.create(slider, {
        start: [0, 1000000],
        connect: true,
        range: {
            min: parseFloat(min),
            max: parseFloat(max),
        },
        step: 10000,
        margin: 600,
        pips: {
            stepped: true,
            density: 6,
        },
    });

    var skipValues = [
        document.getElementById("price_low"),
        document.getElementById("price_high"),
    ];

    slider.noUiSlider.on("update", function (values, handle) {
        skipValues[handle].innerHTML = "$" + values[handle];

        // Here you can use local data or preloaded data instead of making an API request.
        const preResults = localStorage.getItem("results");
        const savedResults = JSON.parse(preResults || '[]'); // Handle null case

        // Filter the saved results based on the slider values
        const filteredResults = savedResults.filter((value) => {
            if (value.data && value.data.price) {
                const price = parseFloat(value.data.price);
                console.log("data.price:", price); // Log the price of each item
                return price >= parseFloat(values[0]) && price <= parseFloat(values[1]);
            }
            return false;
        });

        // Update the results after filtering
        setResults(filteredResults);

        // Optional: Process the filtered data, e.g., encode IDs
        filteredResults.forEach((item) => {
            item.id = btoa(item.id); // Encode the item ID
        });
    });
};


    const search = () => {
        // let filteredResults = dummyResults;
        // if (selectedCategory) {
        //   filteredResults = filteredResults.filter(
        //     (result) => result.category === selectedCategory.value
        //   );
        // }
        // setResults(filteredResults);
    };

    const openInNewTab = (url) => {
        window.open(url, "_blank");
    };
    // State for current page and total pages
    const [currentPage, setCurrentPage] = useState(1);
    const [cardsPerPage] = useState(4); // Number of cards per page

    const totalPages = Math.ceil(results.length / cardsPerPage);
    // Calculate total pages

    // Calculate the cards to display on the current page
    const indexOfLastCard = currentPage * cardsPerPage;
    const indexOfFirstCard = indexOfLastCard - cardsPerPage;
    const currentCards = results.slice(indexOfFirstCard, indexOfLastCard);
    // Function to handle page changes
    const handlePageChange = (newPage) => {
        if (newPage >= 1 && newPage <= totalPages) {
            setCurrentPage(newPage);
        }
    };
    useEffect(() => {
        console.log("Results Length: ", results.length);
        console.log("Total Pages: ", totalPages);
        console.log("Current Cards: ", currentCards);
    }, [results, currentPage]);

    //MAP -- MAP

    const success = (position) => {
        if ((loc == true || loc == "true") && res.length != 0) {
            var myLat = sessionStorage.getItem("queryLat"); // this.queryLat;
            var myLong = sessionStorage.getItem("queryLng"); // this.queryLng;
        } else {
            var myLat = position.coords.latitude;
            var myLong = position.coords.longitude;
        }

        var coords = [myLat, myLong];
        var mapOptions = {
            zoom: 8,
            center: coords,
            //center:new google.maps.LatLng(51.508742,-0.120850),
        };

        //MAP CONTAINER
        let map = new L.map("map", mapOptions);
        let layer = new L.TileLayer(
            "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        );
        map.addLayer(layer);

        Object.entries(res).map(([key, value]) => {
            //INFO
            const contentString =
                '<a class="info_map py-0 font-weight-bold  text-center" target="_blank" href="/service-details/' +
                btoa(btoa(value.id)) +
                '">' +
                value.name +
                "</a>";

            //INFO
            const investment_needed = value.investment_needed / 1000 + "K";
            //this.addMarker({lat:value.lat, lng:value.lng},map,value.name,investment_needed,infowindow);
            var coord = [value.lat, value.lng];
            addMarker(coord, map, contentString);
        });

        addMarkerHome(coords, map);
    };

    const addMarker = (coords, map, contentString) => {
        let customIcon = {
            iconUrl: "../../images/map/other_business.png",
            iconSize: [32, 32],
        };
        let myIcon = L.icon(customIcon);

        let iconOptions = {
            title: "Spurs",
            draggable: true,
            icon: myIcon,
        };

        var marker = new L.Marker(coords, iconOptions);
        marker.addTo(map);
        marker.bindPopup(contentString).openPopup();
    };

    const addMarkerHome = (coords, map) => {
        let customIcon = {
            iconUrl: "../../images/map/myloc.png",
            iconSize: [32, 32],
        };
        let myIcon = L.icon(customIcon);

        let iconOptions = {
            title: "Spurs",
            draggable: true,
            icon: myIcon,
        };

        var marker = new L.Marker(coords, iconOptions);
        marker.addTo(map);
    };

    const failure = () => {};
    //MAP -- MAP

    return (
        <>
            <BackBtn />
            <div className="w-full mx-auto px-4 sm:px-8 md:px-16 lg:px-24">
                {/* <h1 className="text-3xl pt-4 md:text-[64px] mb-8 md:mb-16 font-semibold leading-tight md:leading-[79.36px] tracking-[0.02em] text-center font-sharp-grotesk text-[#00290F]">
                What Are You Looking For?
            </h1> */}
                <div className="mt-6 sm:mt-8 md:mt-10 lg:mt-12 xl:mt-16">
                    <ServiceSearch />
                </div>

                {/* <div className="flex mb-6 flex-col md:flex-row gap-4 justify-center pt-8 px-2 sm:px-6 md:px-4 items-center w-full max-w-3xl mx-auto">
              <input
                  type="text"
                  className="border py-2 text-md px-4 border-[#666666]/30 rounded-xl focus:outline-none w-full md:flex-1"
                  placeholder="What are you looking for?"
                  style={{ textAlign: "center" }}
              />
              <div className="relative w-full md:flex-1">
                  <input
                      type="text"
                      placeholder="Location"
                      className="border border-[#666666]/30 w-full text-md rounded-xl py-2 px-10 focus:outline-none"
                      style={{ textAlign: "center" }}
                      ref={locationInputRef}
                  />
                  <FontAwesomeIcon
                      icon={faLocationDot}
                      className="absolute right-3 ml-2 top-1/2 transform -translate-y-1/2 text-black cursor-pointer"
                  />
              </div>
              <Select
                  className="w-full md:flex-1"
                  options={categories}
                  value={selectedCategory}
                  onChange={setSelectedCategory}
                  placeholder="Select a category"
                  isClearable
                  styles={{
                      control: (provided) => ({
                          ...provided,
                          borderRadius: "12px",
                          padding: "2px 0", // Adjust this value as needed
                      }),
                  }}
              />
              <button
                  className="btn-primary w-full md:w-auto py-3 rounded-full px-4 focus:outline-none mt-4 md:mt-0"
                  onClick={search}
              >
                  <FontAwesomeIcon icon={faSearch} />
              </button>
          </div> */}

                <div className="flex flex-col lg:flex-row items-center gap-6 my-6">
                    <div
                        id="turnover_slider"
                        className=" w-full jakarta  text-md border border-[#cbd5e1] rounded-lg space-y-2 px-6 py-4 "
                    >
                        <label className="text-gray-700 font-semibold mb-2">
                            Price Range
                        </label>
                        <div id="slider" class="">
                            {" "}
                        </div>
                        <div className="row mt-3 jakarta">
                            <div className="col-6  mt-1">
                                <span
                                    id="price_low"
                                    className="py-0 "
                                    name="min"
                                >
                                    {" "}
                                </span>
                            </div>
                            <div className="col-6 mt-1 pr-0">
                                <span
                                    id="price_high"
                                    className="float-right py-0 "
                                    name="min"
                                >
                                    {" "}
                                </span>
                            </div>
                        </div>
                    </div>
                    {/*<PriceRangeFilter />*/}
                </div>

                <h1 className=" text-gray-700 text-2xl mb-2   font-semibold ">
                    <b>{count} Results Found</b>
                </h1>

                <div className="min-h-screen grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 items-start">
                    {/* Results Section */}
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                        {results.length === 0 ? (
                            <div className="space-y-4">
                                {/* Skeleton Loader for Cards */}
                                {[...Array(3)].map((_, index) => (
                                    <div
                                        key={index}
                                        className="border p-5 border-[#0000001A]/10 shadow-sm bg-white h-[500px] rounded-2xl flex flex-col w-full max-w-[900px] mx-auto animate-pulse"
                                    >
                                        {/* Skeleton Image */}
                                        <div className="bg-gray-200 w-full h-[250px] rounded-lg"></div>

                                        <div className="flex flex-col pt-2 justify-between flex-grow p-0">
                                            {/* Skeleton Tags */}
                                            <div className="flex flex-wrap gap-2 text-xs font-semibold text-[#1E293B]">
                                                <div className="bg-gray-200 w-20 h-4 rounded-md"></div>
                                                <div className="bg-gray-200 w-20 h-4 rounded-md"></div>
                                            </div>
                                        </div>

                                        <div className="flex flex-col justify-between flex-grow">
                                            {/* Skeleton Title */}
                                            <div className="bg-gray-200 w-3/4 h-6 rounded-md mt-2"></div>

                                            {/* Skeleton Details */}
                                            <div className="bg-gray-200 w-full h-4 rounded-md mt-2"></div>

                                            {/* Skeleton Category */}
                                            <div className="bg-gray-200 w-1/4 h-4 rounded-md mt-2"></div>

                                            <div className="text-sm text-gray-500 flex flex-col gap-1">
                                                {/* Skeleton Location */}
                                                <div className="bg-gray-200 w-3/4 h-4 rounded-md"></div>

                                                {/* Skeleton Contact */}
                                                <div className="bg-gray-200 w-3/4 h-4 rounded-md"></div>
                                            </div>

                                            {/* Skeleton Price */}
                                            <div className="bg-gray-200 w-1/3 h-6 rounded-md mt-2"></div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        ) : (
                            currentCards.map((row) => (
                                <Link
                                    to={`/service-details/${btoa(
                                        btoa(row.id)
                                    )}`}
                                    key={row.id}
                                >
                                    <div className="border p-5 border-[#0000001A]/10 shadow-sm bg-white h-[500px] rounded-2xl flex flex-col w-full max-w-[900px] mx-auto">
                                        <div>
                                            <img
                                                src={"../../" + row.image}
                                                alt={row.listing_name}
                                                className="w-full h-[250px] object-cover rounded-lg"
                                            />
                                        </div>

                                        <div className="flex flex-col pt-2 justify-between flex-grow">
                                            <div className="flex flex-wrap gap-2 text-xs font-semibold text-[#1E293B]">
                                                {(
                                                    row.tags || [
                                                        "example",
                                                        "dummy",
                                                    ]
                                                ).map((tag) => (
                                                    <span
                                                        key={tag}
                                                        className="text-[#1E293B] font-semibold"
                                                    >
                                                        #{tag}
                                                    </span>
                                                ))}
                                            </div>
                                        </div>

                                        <div className="flex flex-col justify-between flex-grow">
                                            <p className="text-lg font-semibold text-slate-800">
                                                {row.name}
                                            </p>
                                            <p className="text-sm text-gray-600">
                                                {row.details ||
                                                    "Lorem ipsum dolor sit amet consectetur..."}
                                            </p>
                                            <p className="text-sm text-gray-600 inline-block">
                                                {row.category}
                                            </p>

                                            <div className="text-sm text-gray-500 flex flex-col gap-1">
                                                <p className="flex items-center">
                                                    <FontAwesomeIcon
                                                        icon={faLocationDot}
                                                        className="mr-1 text-slate-500"
                                                    />
                                                    {row.location}
                                                </p>
                                                <p className="flex items-center truncate">
                                                    <FontAwesomeIcon
                                                        icon={faPhone}
                                                        className="mr-1 text-slate-500"
                                                    />
                                                    {row.contact ||
                                                        "+1791205437"}
                                                </p>
                                            </div>

                                            <p className="text-green-600 font-bold mt-2">
                                                ${row.price}
                                                <span className="text-gray-500 ml-1 text-xs">
                                                    / Price
                                                </span>
                                            </p>
                                        </div>
                                    </div>
                                </Link>
                            ))
                        )}
                    </div>

                    {/* Map Section */}
                    <div className="h-[500px] sticky top-0 rounded-lg flex items-center justify-center">
                        <div
                            className="m-auto map_style w-full h-full"
                            style={{
                                borderRadius: "16px",
                                overflow: "hidden",
                            }}
                        >
                            <div
                                id="map"
                                style={{
                                    height: "100%",
                                    width: "100%",
                                    borderRadius: "16px",
                                }}
                            ></div>
                        </div>
                    </div>

                    {/* Pagination Section */}
                    <div className="flex justify-start ml-6 mt-4">
                        <CardsPagination
                            currentPage={currentPage}
                            totalPages={totalPages}
                            onPageChange={handlePageChange}
                        />
                    </div>
                </div>
            </div>
        </>
    );
};

export default ServiceResults;

// resources/js/components/site/serviceResults.vue
<template>
    <div class="container bg-white" id="">


        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <h3 class="text-center font-weight-bold"><b class="h5 text-success"> </b> </h3>


        <div class="clear"></div>




        <div class="clear"></div>






        <!-- <div class="content_bottom">
            <div class="heading">
                <h3 class="my-5 text-center secondary_heading">Services</h3>
            </div>
            <div class="clear"></div>
        </div> -->

<form id="form" @submit.prevent="search();" method="post">

      <!-- Search Options and Button Section -->
<div class="flex flex-col sm:flex-row lg:flex-row lg:justify-center sm:justify-start items-center gap-4 sm:gap-16 px-2">
    <div class="my-2">
        <div class="flex items-center">
        <input class="py-2 px-4 rounded-full border border-black w-[250px] focus:outline-none focus:ring-0 focus:border-transparent" type="text" name="listing_name" placeholder="What are you looking for?">
    </div>
    </div>

    <div class="my-2">
      <div class="relative">
    <input id="searchbox" onkeyup="suggest(this.value);" class="py-2 px-4 w-[250px] border border-gray-300 rounded-full focus:outline-none focus:ring-0 focus:border-transparent" type="text" name="search" value="" placeholder="Location">
    <div class="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
        <svg class="h-4 w-4 fill-current text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path d="M10 2a7 7 0 0 1 7 7c0 4.472-7 11-7 11S3 13.472 3 9a7 7 0 0 1 7-7zm0 2a5 5 0 0 0-5 5c0 2.142 3.094 6.333 5 8 1.906-1.667 5-5.858 5-8a5 5 0 0 0-5-5z"/>
        </svg>
    </div>
    <ul id="suggestion-list" class="absolute w-[250px] bg-white  border-t-0 rounded-b-md shadow-lg z-10 top-full">
        <!-- Suggestions will be dynamically added here -->
    </ul>
    <!-- Search Results Section -->
    <div id="result_list" class="absolute w-[250px] bg-white  border-gray-300 border-t-0 rounded-b-md shadow-lg z-10 top-full">
        <!-- Search results will be dynamically added here -->
    </div>
    <!-- End of Search Results Section -->
</div>




    </div>



<div class="w-[162px] my-2">
  <div class="relative">
    <select id="category" name="category"
      class="py-2 px-4 w-full border border-gray-300 rounded-full appearance-none">
      <option value="">Category</option>
<option value="Agriculture">Agriculture</option>
<option value="Arts/Culture">Arts/Culture</option>
<option value="Auto">Auto</option>
<option value="Domestic (Home Help etc)">Domestic (Home Help etc)</option>
<option value="Fashion">Fashion</option>
<option value="Finance/Accounting">Finance/Accounting</option>
<option value="Food">Food</option>
<option value="Legal">Legal</option>
<option value="Media/Internet">Media/Internet</option>
<option value="Other">Other</option>
<option value="Pets">Pets</option>
<option value="Real State">Real State</option>
<option value="Retail">Retail</option>
<option value="Security">Security</option>
<option value="Sports/Gaming">Sports/Gaming</option>
<option value="Technology/Communications">Technology/Communications</option>

    </select>
    <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
      <svg class="h-4 w-4 fill-current text-gray-500" xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20">
        <path
          d="M10 12a1 1 0 0 1-.7-.29l-4-4a1 1 0 1 1 1.4-1.42L10 9.58l3.3-3.3a1 1 0 1 1 1.4 1.42l-4 4a1 1 0 0 1-.7.3z" />
      </svg>
    </div>
  </div>
</div>


        <div class="w-12 h-12 my-2 bg-green-700 rounded-[50%] flex items-center justify-center">
          <button type="submit" class="py-2 px-6  text-white rounded-full"><i class="fa fa-search"></i></button>
        </div>
      </div>
      <!-- End of Search Options and Button Section -->


    <input type="text" name="lat" id="lat" hidden value="">
    <input type="text" name="lng" id="lng" hidden value="">    
    </form>



<div class="flex  gap-1 ">
                    <div class=""><span style="" class=" text-black px-2 py-1 rounded">Filter by
                            Price:</span></div>
                    <div id="" class="col-sm-5  mt-1">
                        <div id="slider" class=""> </div>
                        <div class="row mt-3">
                            <div class="col-6  mt-1">
                                <span id="price_low" class="py-0 btn btn-light" name="min"> </span>
                            </div>
                            <div class="col-6 mt-1 pr-0">
                                <span id="price_high" class="float-right py-0 btn btn-light" name="min"> </span>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <!-- <a class="py-0 float-right border border-dark rounded" style="width:70px; height:40px;">
                            <div class="row">
                                <div class="col-6 pr-0">
                                    <p style="font-size:12px;" class="text-dark">More Filters</p>
                                </div>
                                <div class="col-6 px-1"> <img src="images/randomIcons/filter.jpg" width="20px;"
                                        style="margin-left:5px;">
                                </div>
                            </div>
                        </a>
 -->
                    </div>

                </div>

        <div class="row mt-4 row flex-column-reverse flex-md-row">

            <div class="col-md-6 " style="height: 100vh; overflow-y: scroll;  overflow-anchor: auto;">
                <!-- Price Filter -->
                <div class="row hidden">
                    <div class="col-sm-3"><span style="background:black;" class="btn text-light px-2 py-1 rounded">Filter by
                            Price:</span></div>
                    <div id="" class="col-sm-5  mt-1">
                        <div id="slider" class=""> </div>
                        <div class="row mt-3">
                            <div class="col-6  mt-1">
                                <span id="price_low" class="py-0 btn btn-light" name="min"> </span>
                            </div>
                            <div class="col-6 mt-1 pr-0">
                                <span id="price_high" class="float-right py-0 btn btn-light" name="min"> </span>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <!-- <a class="py-0 float-right border border-dark rounded" style="width:70px; height:40px;">
                            <div class="row">
                                <div class="col-6 pr-0">
                                    <p style="font-size:12px;" class="text-dark">More Filters</p>
                                </div>
                                <div class="col-6 px-1"> <img src="images/randomIcons/filter.jpg" width="20px;"
                                        style="margin-left:5px;">
                                </div>
                            </div>
                        </a>
 -->
                    </div>

                </div>
                <div class="row">
                    <p class="ml-1 my-0 text-black font-bold small">{{ count }} Services  found<!-- your location --></p>
                </div>
                <!-- Price Filter -->

                <div class="row" v-if="count != 0">
                    <div v-for="( result, index ) in results" class="listing row  my-3">
                       <a :href="'./#/serviceDetails/'+result.id" class="flex px-4">
                            <div class="flex items-center gap-[30px] mb-5 w-full rounded-[30px] h-[200px]" style="box-shadow: rgba(0, 0, 0, 0.05) 0px 6px 24px 0px, rgba(0, 0, 0, 0.08) 0px 0px 0px 1px;">
                            <!-- image or video -->


                      <div class="rounded-l-lg">
    <video v-if="result.file" controls style="width: 200px !important; height: 200px !important; border-left: 2px solid white; border-radius: 30px; object-fit: cover !important;" alt="">
        <source :src="result.file" type="video/mp4">
    </video>
    <img class="rounded-l-lg" v-else :src="result.image" style="width: 200px !important; height: 200px !important; border-left: 2px solid white; border-radius: 30px; object-fit: cover !important;" alt="" />
</div>

<div class="pt-2 pb-2">
    <h5 class="card_heading mb-0 py-2">{{ result.name }}</h5>
    <div class="rounded-full">
    <p class="my-1 text-center bg-black text-white rounded-full inline-block py-1 px-2">
        <b>{{ result.category }}</b>
    </p>
</div>

    <div class="pt-1">
        <div class="flex justify-between gap-[50px]">
            <div class="flex justify-between items-center gap-[40px]">
                <div class="flex flex-col gap-2">
                    <p class="text-gray-900 pt-1 text-left ">
                        <i class="mr-2 text-black fa fa-map-marker"></i>{{ result.location }}
                    </p>
                    <div class="flex flex-col  gap-1">
   <!--  <div class="flex items-center gap-2">
        <i class="fa fa-phone"></i>
        <p class="card_text">
            <span class="rounded">{{ result.contact }}</span>
        </p>
    </div> -->

    <div class="whitespace-nowrap  mb-2">
        <!-- <p class="mt-2 font-bold text-black">Yearly Turnover: <span class="font-normal">${{ result.y_turnover }}</span></p> -->
        <p class="mt-1 font-bold text-black">Amount Requested: <span class="font-normal">${{ result.price }}</span></p>
    </div>
</div>

                </div>
               
            </div>
        </div>
    </div>
</div>


                            </div>
                        </a>
                    </div>
                    <div v-for="( result, index ) in results" class="listing col-md-6 my-3 hidden">
                        <router-link :to="`/serviceDetails/${result.id}`" class="shadow card border px-4">

                            <video v-if="result.file" controls style="width:100%; height:230px" alt="">
                                <source :src="result.file" type="video/mp4">
                            </video>

                            <img class="pt-2" v-else :src="result.image" style="width:100%; height:200px" alt="" />

                            <div class="p-1 pb-2">
                                <h5 class="card_heading mb-0 py-2">{{ result.name }} </h5>
                                <p class="my-1 text_color_p font-weight-bold"><i class="mr-2 fa fa-dollar"></i>{{
                                    result.price }}</p>

                                <p class="loc_p card_text pt-1 text-left"><i class="mr-2 fa fa-map-marker"></i>{{ result.location
                                }}</p>

                                <p><span class="mt-1 rounded small"><i class="mr-2 fa fa-category"></i>Category:
                                        {{ result.category }}</span></p>
                            </div>

                        </router-link>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="map_style m-auto">
                    <div id="map" style="height: 95%;"></div> 
                </div>
            </div>

        </div>


        <div class="row mt-4" v-if="this.ids == '0'">
            <h3 class="text-center font-weight-bold btn-light btn py-3 d-block">No Results Found! </h3>
        </div>


    </div>
</div></div></template>

<script>

export default {
    props: ['auth_user'],
    data: () => ({
        results: [],
        ids: '',
        empty: false,
        count: 0,
         loc:'',
        queryLat:'',
        queryLng:''
    }),
    methods: {
        setRes: function () {
            let t = this;
            this.ids = atob(this.$route.params.results);
            //this.results = this.ids.split(",");
            axios.get('ServiceResults/' + t.ids).then((data) => {            
                if(data.data.count != 0){
                t.count = data.data.count;
                t.results = data.data.data;

                 for (const [key, value] of Object.entries(t.results)) {  
                    value.id = btoa(value.id);
                    value.id = btoa(value.id);
                    //console.log(value.id);
                }
                //console.log(data);
                //Setting Curr LatLng
                t.queryLat = data.data.data[0].lat;
                t.queryLng = data.data.data[0].lng;
            }
            }).catch((error) => { console.log(error); })
        },


        range() {
            this.ids = atob(this.$route.params.results);
            let t = this;

            if(t.ids != 'no-results')
            {
            var slider = document.getElementById('slider');
            noUiSlider.create(slider, {
                start: [0, 500000],
                connect: true,
                range: {
                    'min': 0,
                    'max': 500000
                },

                step: 10000,
                margin: 600,
                pips: {
                    //mode: 'steps',
                    stepped: true,
                    density: 6
                }
            });
            var skipValues = [
                document.getElementById('price_low'),
                document.getElementById('price_high')
            ];
            slider.noUiSlider.on('update', function (values, handle) {
                skipValues[handle].innerHTML = '$' + values[handle];
                //console.log(values[1] - values[0]);

                axios.get('priceFilterS/' + values[0] + '/' + values[1] + '/' + t.ids).then((data) => {
                    t.results = '';
                    t.results = data.data.data;
                    t.count = data.data.data.length;

                    for (const [key, value] of Object.entries(t.results)) {  
                    value.id = btoa(value.id);
                    value.id = btoa(value.id);
                    //console.log(value.id);
                }

                    //Setting Curr LatLng
                    t.queryLat = data.data.data[0].lat;
                    t.queryLng = data.data.data[0].lng;

                    //console.log(data);
                }).catch((error) => { })

            });
        }

        },

        getPhoto() {

            return '../';

        },
        cart() {
            //axios.get('cart').then((data) => {
               // document.getElementById('cart').innerHTML = data.data.cart;});
        },

        replaceText() {
            $('#call_to').html('');
            $('#call_to').html('<a onclick="c_to_actionS();" data-target="#loginModal" data-toggle="modal" class="header_buttons px-sm-3 my-1 px-1 py-1 mx-1 d-inline-block small text-center" ><span style="color:black;" id="c_to_ac">Add Your Service</span></a> ');
        },

        //MAP -- MAP

        success(position){
        var loc = this.loc;
        if((loc == true || loc == "true") && this.count !=0){
            var myLat = sessionStorage.getItem('SqueryLat');// this.queryLat;
            var myLong = sessionStorage.getItem('SqueryLng');// this.queryLng;
        }

        else{
             var myLat = position.coords.latitude;
             var myLong = position.coords.longitude;
        } 

        

        var coords = ([myLat,myLong]);
        var mapOptions = {
        zoom:8,
        center:coords,
        //center:new google.maps.LatLng(51.508742,-0.120850),
        }

        //MAP CONTAINER
        let map = new L.map('map' , mapOptions);
        let layer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');
        map.addLayer(layer);
 
        //console.log(this.results);
        for (const [key, value] of Object.entries(this.results)) {
            //INFO

                const contentString = '<a class="info_map py-0 font-weight-bold  text-center" target="_blank" href="https://test.jitume.com/#/serviceDetails/'+value.id+'">'
                +value.name+'</a>';

            //INFO
              const investment_needed = (value.investment_needed/1000)+"K";
              //this.addMarker({lat:value.lat, lng:value.lng},map,value.name,investment_needed,infowindow);
              var coord = ([value.lat,value.lng]);
              this.addMarker(coord,map,contentString);
            }
        

            this.addMarkerHome(coords,map);
        },

        addMarker(coords,map,contentString){
        let customIcon = {
         iconUrl:'images/map/other_business.png',
         iconSize:[32,32]
        }; let myIcon = L.icon(customIcon);

        let iconOptions = {
         title:'Spurs',
         draggable:true,
         icon:myIcon
        }

        var marker = new L.Marker(coords, iconOptions);
        marker.addTo(map);
        marker.bindPopup(contentString).openPopup();
        },

        addMarkerHome(coords,map){
        let customIcon = {
         iconUrl:'images/map/myloc.png',
         iconSize:[32,32]
        }; let myIcon = L.icon(customIcon);

        let iconOptions = {
         title:'Spurs',
         draggable:true,
         icon:myIcon
        }

        var marker = new L.Marker(coords, iconOptions);
        marker.addTo(map);

        },
         failure(){},
        //MAP -- MAP

    },

    mounted() {
        this.loc = this.$route.params.loc;
        this.replaceText();
        this.setRes()
        this.range()
        //this.cart()

        //MAP -- MAP
        var x = navigator.geolocation;
        setTimeout(() => x.getCurrentPosition(this.success, this.failure), 1000);
        //MAP -- MAP

        //return this.$store.dispatch("fetchpro")
    }

}
</script>
