// resources/js/components/site/listingResults.vue
<template>
    <div class="container  bg-white pb-2"  id="">
<div>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <h3 class="text-center font-weight-bold"><b class="h5 text-success"> </b> </h3>


        <div class="clear"></div>




        <div class="clear"></div>



<!-- top -->


<div class="py-2">
    
    <form id="form" @submit.prevent="search();" method="post">

      <!-- Search Options and Button Section -->
<div class="flex flex-col sm:flex-row lg:flex-row lg:justify-center sm:justify-start items-center gap-4 sm:gap-16 px-2">
    <div class="my-2">
        <div class="flex items-center">
        <input class="py-2 px-4 rounded-full border border-black w-[250px] focus:outline-none focus:ring-0 focus:border-transparent" type="text" name="listing_name" placeholder="What are you looking for?">
    </div>
    </div>

    <div class="my-2">
      <div class="relative">
    <input id="searchbox" onkeyup="suggest(this.value);" class="py-2 px-4 w-[250px] border border-gray-300 rounded-full focus:outline-none focus:ring-0 focus:border-transparent" type="text" name="search" value="" placeholder="Location">
    <div class="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
        <svg class="h-4 w-4 fill-current text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path d="M10 2a7 7 0 0 1 7 7c0 4.472-7 11-7 11S3 13.472 3 9a7 7 0 0 1 7-7zm0 2a5 5 0 0 0-5 5c0 2.142 3.094 6.333 5 8 1.906-1.667 5-5.858 5-8a5 5 0 0 0-5-5z"/>
        </svg>
    </div>
    <ul id="suggestion-list" class="absolute w-[250px] bg-white  border-t-0 rounded-b-md shadow-lg z-10 top-full">
        <!-- Suggestions will be dynamically added here -->
    </ul>
    <!-- Search Results Section -->
    <div id="result_list" class="absolute w-[250px] bg-white  border-gray-300 border-t-0 rounded-b-md shadow-lg z-10 top-full">
        <!-- Search results will be dynamically added here -->
    </div>
    <!-- End of Search Results Section -->
</div>




    </div>



        <div class="w-[162px] my-2">
  <div class="relative">
    <select id="category" name="category"
      class="py-2 px-4 w-full border border-gray-300 rounded-full appearance-none">
      <option value="">Category</option>
<option value="Agriculture">Agriculture</option>
<option value="Arts/Culture">Arts/Culture</option>
<option value="Auto">Auto</option>
<option value="Domestic (Home Help etc)">Domestic (Home Help etc)</option>
<option value="Fashion">Fashion</option>
<option value="Finance/Accounting">Finance/Accounting</option>
<option value="Food">Food</option>
<option value="Legal">Legal</option>
<option value="Media/Internet">Media/Internet</option>
<option value="Other">Other</option>
<option value="Pets">Pets</option>
<option value="Real State">Real State</option>
<option value="Retail">Retail</option>
<option value="Security">Security</option>
<option value="Sports/Gaming">Sports/Gaming</option>
<option value="Technology/Communications">Technology/Communications</option>

    </select>
    <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
      <svg class="h-4 w-4 fill-current text-gray-500" xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20">
        <path
          d="M10 12a1 1 0 0 1-.7-.29l-4-4a1 1 0 1 1 1.4-1.42L10 9.58l3.3-3.3a1 1 0 1 1 1.4 1.42l-4 4a1 1 0 0 1-.7.3z" />
      </svg>
    </div>
  </div>
</div>


        <div class="w-12 h-12 my-2 bg-green-700 rounded-[50%] flex items-center justify-center">
          <button type="submit" class="py-2 px-6  text-white rounded-full"><i class="fa fa-search"></i></button>
        </div>
      </div>
      <!-- End of Search Options and Button Section -->


      
    </form>


  
<div class="flex py-4  gap-4">

                  <!--   <div class="col-sm-3"><span style="background:black;font-size: 11px;" class="btn text-light px-2 py-1 small rounded">Filter by
                            Turnover Range:</span>
                    </div>   -->


 

                </div>

</div>





        <div class="mt-4 row flex-column-reverse flex-md-row">



            <div class="col-md-8 pr-4 element-class" style="height: 100vh; overflow-y: scroll;  overflow-anchor: auto;">
                <!-- Price Filter -->
                <div class="row">
                    <div class="content_bottom">

                    <div class="flex">
                    <div class="col-sm-3"><span style="background:black;font-size: 11px;" class="btn text-light px-2 py-1 small rounded">Filter by Turnover Range:</span>
                    </div>  
                    <div id="" class="col-sm-6 mt-1"> 
                        <div id="slider" class=""> </div>
                        <div class="row mt-3">
                            <div class="col-6  mt-1">
                                <span id="price_low" class="py-0 btn btn-light" name="min"> </span>
                            </div>
                            <div class="col-6 mt-1 pr-0">
                                <span id="price_high" class="float-right py-0 btn btn-light" name="min"> </span>
                            </div>
                        </div>
                    </div>
                    </div>


                    <div class="flex">
                    <div class="col-sm-3"><span style="background:black;font-size: 11px;" class="btn text-light px-2 py-1 small rounded">Filter by Amount R.:</span>
                    </div>  
                    <div id="" class="col-sm-6 mt-1"> 
                        <div id="slider2" class="mt-3"> </div>
                        <div class="row mt-3">
                            <div class="col-6  mt-1">
                                <span id="price_low2" class="py-0 btn btn-light" name="min"> </span>
                            </div>
                            <div class="col-6 mt-1 pr-0">
                                <span id="price_high2" class="float-right py-0 btn btn-light" name="min"> </span>
                            </div>
                        </div>

                    </div>
                    </div>

            <div class="heading">
                <h3 class="my-5 text-2xl font-bold   " style="color:#198754;">Businesses</h3>
            </div>
            <div class="clear"></div>
        </div> 


                   

                    <div class="col-sm-4">
                        <!-- <a class="py-0 float-right border border-dark rounded pointer" style="width:70px; height:40px;">
                            <div class="row">
                                <div class="col-6 pr-0">
                                    <p style="font-size:12px;" class="text-dark">More Filters</p>
                                </div>
                                <div class="col-6 px-1"> <img src="images/randomIcons/filter.jpg" width="20px;"
                                        style="margin-left:5px;">
                                </div>
                            </div>
                        </a> -->

                    </div>

                </div>
                <div class="row">
                    <p class="ml-1 my-0 text-gray-600 small">{{ count }} businesses found<!-- in your location --></p>
                </div>
                <!-- Price Filter -->




                <div class="">
                    <div v-for="( result, index ) in results" class="listing row  my-3">
                        <router-link :to="`/listingDetails/${result.id}`" class=" flex  px-4">

                            <div class="flex items-center gap-4 mb-5  rounded-[30px] h-[200px]" style="box-shadow: rgba(0, 0, 0, 0.05) 0px 6px 24px 0px, rgba(0, 0, 0, 0.08) 0px 0px 0px 1px;">
                            <!-- image or video -->


                          <div class="rounded-l-lg">
    <video v-if="result.file" controls style="width: 500px !important; height: 200px !important; border-left: 2px solid white; border-radius: 30px; object-fit: cover !important;" alt="">
        <source :src="result.file" type="video/mp4">
    </video>

    <img class="rounded-l-lg" v-else :src="result.image" style="width: 500px !important; height: 200px !important; border-left: 2px solid white; border-radius: 30px; object-fit: cover !important;" alt="" />
</div>

                           

                            <div class="p-1 pb-2">
                                <h5 class="card_heading mb-0 py-2">{{ result.name }} </h5>

                                <div class="  rounded-full">

                                <p class=" my-2 text-center bg-black  rounded-full w-[110px] text-white "><b></b> {{ result.category }}</p>

                                </div>

                                <div class="pt-4">


                               

                               <div class="flex justify-between   gap-[70px]">
<div class="flex justify-between items-center  gap-[40px]">
    <div class="flex flex-col gap-2">
         <p class=" text-gray-900 pt-1 text-left   truncate"><i class="mr-2 text-black fa fa-map-marker"></i>{{ result.location
                                }}</p>

                                <div class="flex items-center gap-1">
                                     
                                    <i class="mr-2 fa fa-phone"></i>
        <p class="card_text"><span class="rounded">{{ result.contact }}</span></p>
                                </div>
        
    </div>

    <div class="flex flex-col whitespace-nowrap p-2">
        <p class="mt-2">Yearly Turnover: <span class="font-normal">${{ result.y_turnover }}</span></p>
        <p class="mt-1">Amount Requested: <span class="font-normal">${{ result.investment_needed }}</span></p>
    </div>
</div>


    <!-- <div class="flex flex-col items-end mt-4 pr-2 space-y-1">
        <p class="small amount whitespace-nowrap font-extrabold text-black">Yearly Turnover: 
            <span class="font-normal">${{ result.y_turnover }}</span>
        </p>
        <p class="small amount whitespace-nowrap font-extrabold text-black">Amount Required: 
            <span class="font-normal">${{ result.investment_needed }}</span>
        </p>
    </div> -->
</div>


                                </div>
                            </div>

                            

                            </div>
                        </router-link>
                    </div>
                </div>
            </div>

           <!--  <div class="col-md-4">
                <div class="m-auto map_style" >
                     <div id="map" style="height: 100%; border: 30px;"></div> 
                </div>
            </div> -->

             <div class="col-md-4">
                <div class="m-auto map_style">
                     <div id="map" style="height: 95%;"></div> 
                </div>
            </div>

        </div>


        <div class="row mt-4" v-if="this.ids == '0'">
            <h3 class="text-center font-weight-bold btn-light btn py-3 d-block">No Results Found! </h3>
        </div>

</div>
    </div>
</div>

</div>

</template>



<script>

//import {myMap,success,failure,addMarker,addMarkerHome} from '../../../../public/js/map'

export default {
    props: ['auth_user', 'app_url'],
    data: () => ({
        results: [],
        results2: [],
        ids: '',
        empty: false,
        count: 0,
        loc:'',
        queryLat:'',
        queryLng:''
    }),

    
    methods: {
        setRes: function () {
            let t = this;
            this.ids = atob(this.$route.params.results);
            //this.results = this.ids.split(",");
            if(t.ids != 0) {
            axios.get('searchResults/' + t.ids).then((data) => {
                //t.results2 = data.data.data;
                t.results = data.data.data;

                for (const [key, value] of Object.entries(t.results)) {
                    
                    value.id = btoa(value.id);
                    value.id = btoa(value.id);
                    //console.log(value.id);
                }

                t.count = data.data.count;
                
                //Setting Curr LatLng
                t.queryLat = data.data.data[0].lat;
                t.queryLng = data.data.data[0].lng;
                //console.log(t.results);
            }).catch((error) => { })
        }
        },

        getPhoto() {

            return '../';

        },

        range() {
            this.ids = atob(this.$route.params.results);
            let t = this;

            if(t.ids != 0) {
            var slider = document.getElementById('slider');
            noUiSlider.create(slider, {
                start: [0, 500000],
                connect: true,
                range: {
                    'min': 0,
                    'max': 500000
                },

                step: 10000,
                margin: 600,
                pips: {
                    //mode: 'steps',
                    stepped: true,
                    density: 6
                }
            });
            var skipValues = [
                document.getElementById('price_low'),
                document.getElementById('price_high')
            ];
            slider.noUiSlider.on('update', function (values, handle) {
                skipValues[handle].innerHTML = '$' + values[handle];
                //console.log(values[1] - values[0]);

                axios.get('priceFilter/' + values[0] + '/' + values[1] + '/' + t.ids).then((data) => {

                    // if(values[0]==0.00 && values[1]==500000.00){}
                    //else{ 

                    t.count = data.data.data.length;
                    t.results = '';
                    t.results = data.data.data;

                    for (const [key, value] of Object.entries(t.results)) {
                    
                    value.id = btoa(value.id);
                    value.id = btoa(value.id);
                }

                    t.queryLat = data.data.data[0].lat;
                    t.queryLng = data.data.data[0].lng;
                        

                    //}
                    //console.log(t.results);
                }).catch((error) => { })

            });
        }

        },

       range_amount() {
            this.ids = atob(this.$route.params.results);
            let t = this;

            if(t.ids != 0) {
            var slider = document.getElementById('slider2');
            noUiSlider.create(slider, {
                start: [0, 15000000],
                connect: true,
                range: {
                    'min': 10000,
                    'max': 15000000
                },

                step: 10000,
                margin: 600,
                pips: {
                    //mode: 'steps',
                    stepped: true,
                    density: 6
                }
            });
            var skipValues = [
                document.getElementById('price_low2'),
                document.getElementById('price_high2')
            ];
            slider.noUiSlider.on('update', function (values, handle) {
                skipValues[handle].innerHTML = '$' + values[handle];
                //console.log(values[1] - values[0]);

                axios.get('priceFilter_amount/' + values[0] + '/' + values[1] + '/' + t.ids).then((data) => {

                    // if(values[0]==0.00 && values[1]==500000.00){}
                    //else{ 

                    t.count = data.data.data.length;
                    t.results = '';
                    t.results = data.data.data;

                    for (const [key, value] of Object.entries(t.results)) {
                    
                    value.id = btoa(value.id);
                    value.id = btoa(value.id);
                }

                    t.queryLat = data.data.data[0].lat;
                    t.queryLng = data.data.data[0].lng;
                        

                    //}
                    //console.log(t.results);
                }).catch((error) => { })

            });
        }

        },

        //MAP -- MAP

        success(position){
        var loc = this.loc;
        if((loc == true || loc == "true") && this.count !=0){
            var myLat = sessionStorage.getItem('queryLat');// this.queryLat;
            var myLong = sessionStorage.getItem('queryLng');// this.queryLng;
        }

        else{
             var myLat = position.coords.latitude;
             var myLong = position.coords.longitude;
        } 

        

        var coords = ([myLat,myLong]);
        var mapOptions = {
        zoom:8,
        center:coords,
        //center:new google.maps.LatLng(51.508742,-0.120850),
        }

        //MAP CONTAINER
        let map = new L.map('map' , mapOptions);
        let layer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');
        map.addLayer(layer);
 
        //console.log(this.results);
        for (const [key, value] of Object.entries(this.results)) {
            //INFO

                const contentString = '<a class="info_map py-0 font-weight-bold  text-center" target="_blank" href="https://test.jitume.com/#/listingDetails/'+value.id+'">'
                +value.name+'</a>';

            //INFO
              const investment_needed = (value.investment_needed/1000)+"K";
              //this.addMarker({lat:value.lat, lng:value.lng},map,value.name,investment_needed,infowindow);
              var coord = ([value.lat,value.lng]);
              this.addMarker(coord,map,contentString);
            }
        

            this.addMarkerHome(coords,map);
        },

        addMarker(coords,map,contentString){
        let customIcon = {
         iconUrl:'images/map/other_business.png',
         iconSize:[32,32]
        }; let myIcon = L.icon(customIcon);

        let iconOptions = {
         title:'Spurs',
         draggable:true,
         icon:myIcon
        }

        var marker = new L.Marker(coords, iconOptions);
        marker.addTo(map);
        marker.bindPopup(contentString).openPopup();
        },

        addMarkerHome(coords,map){
        let customIcon = {
         iconUrl:'images/map/myloc.png',
         iconSize:[32,32]
        }; let myIcon = L.icon(customIcon);

        let iconOptions = {
         title:'Spurs',
         draggable:true,
         icon:myIcon
        }

        var marker = new L.Marker(coords, iconOptions);
        marker.addTo(map);

        },

        failure(){},
        //MAP -- MAP

    },

    mounted() {
        this.loc = this.$route.params.loc;
        this.setRes()
        this.range()
        this.range_amount()

        var x = navigator.geolocation;
        setTimeout(() => x.getCurrentPosition(this.success, this.failure), 1000);

        //return this.$store.dispatch("fetchpro")
    }

}
</script>

// React/src/components/partials/listingResults.jsx
import { useState, useRef, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import Select from "react-select";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faLocationDot,
    faSearch,
    faPhone,
} from "@fortawesome/free-solid-svg-icons";
import Footer from "./footer";
import PriceRangeFilter from "./PriceRangeFilter";
import Navbar from "./Navbar";
import axiosClient from "../../axiosClient";
import { Link } from "react-router-dom";
import { useStateContext } from "../../contexts/contextProvider";
import { decode as base64_decode, encode as base64_encode } from "base-64";
import ListingSearch from "../partials/ListingSearch";
// import noUiSlider from 'nouislider';
// import 'nouislider/dist/nouislider.css';
import CardsPagination from "./CardsPagination";
import Search from "../partials/ListingSearch";
import BackBtn from "./BackBtn";

// Dummy data
const ListingResults = () => {
    const categories = [
        { value: "Agriculture", label: "Agriculture" },
        { value: "Arts/Culture", label: "Arts/Culture" },
        { value: "Auto", label: "Auto" },
        {
            value: "Domestic (Home Help etc)",
            label: "Domestic (Home Help etc)",
        },
        { value: "Fashion", label: "Fashion" },
        { value: "Finance/Accounting", label: "Finance/Accounting" },
        { value: "Food", label: "Food" },
        { value: "Legal", label: "Legal" },
        { value: "Media/Internet", label: "Media/Internet" },
        { value: "Other", label: "Other" },
        { value: "Pets", label: "Pets" },
        { value: "Real Estate", label: "Real Estate" },
        { value: "Retail", label: "Retail" },
        { value: "Security", label: "Security" },
        { value: "Sports/Gaming", label: "Sports/Gaming" },
        {
            value: "Technology/Communications",
            label: "Technology/Communications",
        },
    ];

    const { resIds } = useParams();
    const { loc } = useParams();

    const [selectedCategory, setSelectedCategory] = useState(null);
    const [results, setResults] = useState("");
    const [priceRange, setPriceRange] = useState([0, 1000]); // Initial range
    const locationInputRef = useRef(null);
    const sliderRef = useRef(null);

    const mapRef = useRef(null);

    var count = results.length;
    let res = [];
    var max = 1000000;
    var min = 0;
    var max2 = 1000000;
    var min2 = 0;

    const openInNewTab = (url) => {
        window.open(url, "_blank");
    };
    // State for current page and total pages
    const [currentPage, setCurrentPage] = useState(1);
    const [cardsPerPage] = useState(4); // Number of cards per page

    const totalPages = Math.ceil(results.length / cardsPerPage);
    // Calculate total pages

    // Calculate the cards to display on the current page
    const indexOfLastCard = currentPage * cardsPerPage;
    const indexOfFirstCard = indexOfLastCard - cardsPerPage;
    const currentCards = results.slice(indexOfFirstCard, indexOfLastCard);
    // Function to handle page changes
    const handlePageChange = (newPage) => {
        if (newPage >= 1 && newPage <= totalPages) {
            setCurrentPage(newPage);
        }
    };

    useEffect(() => {
        console.log("Results Length: ", results.length);
        console.log("Total Pages: ", totalPages);
        console.log("Current Cards: ", currentCards);
    }, [results, currentPage]);

    //CORE METHODS
    useEffect(() => {
        const getResults = () => {
            axiosClient
                .get("/searchResults/" + base64_decode(resIds))
                .then(({ data }) => {
                    setResults(data.data);
                    res = data.data;
                    console.log(data);
                    var x = navigator.geolocation;
                    x.getCurrentPosition(success, failure);
                    // document.querySelector('.permission-granted-button').addEventListener('click', () => {
                    //   x.watchPosition(success, failure);
                    // });
                })
                .catch((err) => {
                    console.log(err);
                });
        };
        getResults();
        //console.log(res);

        const onChangeSlider = () => {
            alert("slider is moving");
        };

        //x.getCurrentPosition(success, failure);
        var slider = document.getElementById("slider");
        var slider2 = document.getElementById("slider2");

        if ((slider && slider.noUiSlider) || (slider2 && slider2.noUiSlider)) {
            slider.noUiSlider.destroy();
            slider2.noUiSlider.destroy();
        }

        const rangeSlider = () => {
            //var slider = document.getElementById('slider');
            noUiSlider.create(slider, {
                start: [0, 1000000],
                connect: true,
                range: {
                    min: parseFloat(min),
                    max: parseFloat(max),
                },

                step: 10000,
                margin: 600,
                pips: {
                    //mode: 'steps',
                    stepped: true,
                    density: 6,
                },
            });
            var skipValues = [
                document.getElementById("price_low"),
                document.getElementById("price_high"),
            ];
            slider.noUiSlider.on("update", function (values, handle) {
                skipValues[handle].innerHTML = "$" + values[handle];
                //console.log(values[1] - values[0]);

                // setTimeout(() => {
                axiosClient
                    .get(
                        "priceFilter/" +
                            values[0] +
                            "/" +
                            values[1] +
                            "/" +
                            base64_decode(resIds)
                    )
                    .then((data) => {
                        //count = data.data.length;
                        setResults("");
                        setResults(data.data.data);

                        console.log(data.data.data);

                        for (const [key, value] of Object.entries(data.data)) {
                            value.id = btoa(value.id);
                            value.id = btoa(value.id);
                        }
                        // t.queryLat = data.data.data[0].lat;
                        // t.queryLng = data.data.data[0].lng;
                    })
                    .catch((error) => {});
                // }, 1000)
            });
        };

        const amountSlider = () => {
            noUiSlider.create(slider2, {
                start: [0, 1000000],
                connect: true,
                range: {
                    min: parseFloat(min2),
                    max: parseFloat(max2),
                },

                step: 10000,
                margin: 600,
                pips: {
                    //mode: 'steps',
                    stepped: true,
                    density: 6,
                },
            });
            var skipValues = [
                document.getElementById("price_low2"),
                document.getElementById("price_high2"),
            ];
            slider2.noUiSlider.on("update", function (values, handle) {
                skipValues[handle].innerHTML = "$" + values[handle];
                //console.log(values[1] - values[0]);

                // setTimeout(() => {
                axiosClient
                    .get(
                        "priceFilter_amount/" +
                            values[0] +
                            "/" +
                            values[1] +
                            "/" +
                            base64_decode(resIds)
                    )
                    .then((data) => {
                        //count = data.data.length;
                        setResults("");
                        setResults(data.data.data);
                        console.log(data.data.data);

                        for (const [key, value] of Object.entries(data.data)) {
                            value.id = btoa(value.id);
                            value.id = btoa(value.id);
                        }
                        // t.queryLat = data.data.data[0].lat;
                        // t.queryLng = data.data.data[0].lng;
                    })
                    .catch((error) => {});
                // }, 1000)
            });
        };

        rangeSlider();
        amountSlider();
    }, []);

    //MAP -- MAP

    const success = (position) => {
        if ((loc == true || loc == "true") && res.length != 0) {
            var myLat = sessionStorage.getItem("queryLat"); // this.queryLat;
            var myLong = sessionStorage.getItem("queryLng"); // this.queryLng;
        } else {
            var myLat = position.coords.latitude;
            var myLong = position.coords.longitude;
        }

        var coords = [myLat, myLong];
        var mapOptions = {
            zoom: 8,
            center: coords,
            //center:new google.maps.LatLng(51.508742,-0.120850),
        };

        //MAP CONTAINER
        let map = new L.map("map", mapOptions);
        let layer = new L.TileLayer(
            "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        );
        map.addLayer(layer);

        Object.entries(res).map(([key, value]) => {
            //INFO
            const contentString =
                '<a className="info_map py-0 font-weight-bold  text-center" target="_blank" href="/listing/' +
                btoa(btoa(value.id)) +
                '">' +
                value.name +
                "</a>";

            //INFO
            const investment_needed = value.investment_needed / 1000 + "K";
            //this.addMarker({lat:value.lat, lng:value.lng},map,value.name,investment_needed,infowindow);
            var coord = [value.lat, value.lng];
            addMarker(coord, map, contentString);
        });

        addMarkerHome(coords, map);
    };

    const addMarker = (coords, map, contentString) => {
        let customIcon = {
            iconUrl: "../../images/map/other_business.png",
            iconSize: [32, 32],
        };
        let myIcon = L.icon(customIcon);

        let iconOptions = {
            title: "Spurs",
            draggable: true,
            icon: myIcon,
        };

        var marker = new L.Marker(coords, iconOptions);
        marker.addTo(map);
        marker.bindPopup(contentString).openPopup();
    };

    const addMarkerHome = (coords, map) => {
        let customIcon = {
            iconUrl: "../../images/map/myloc.png",
            iconSize: [32, 32],
        };
        let myIcon = L.icon(customIcon);

        let iconOptions = {
            title: "Spurs",
            draggable: true,
            icon: myIcon,
        };

        var marker = new L.Marker(coords, iconOptions);
        marker.addTo(map);
    };

    const failure = () => {};
    //MAP -- MAP

    return (
        <>
            <BackBtn />
            <div className="w-full mx-auto px-4 sm:px-8 md:px-16 lg:px-24">
                {/* <div className="flex mb-6 flex-col md:flex-row gap-4 justify-center pt-8 px-2 sm:px-6 md:px-4 items-center w-full max-w-3xl mx-auto">
                <input
                    type="text"
                    className="border py-2 text-md px-4 border-[#666666]/30 rounded-xl focus:outline-none w-full md:flex-1"
                    placeholder="What are you looking for?"
                    style={{ textAlign: "center" }}
                />
                <div className="relative w-full md:flex-1">
                    <input
                        type="text"
                        placeholder="Location"
                        className="border border-[#666666]/30 w-full text-md rounded-xl py-2 px-10 focus:outline-none"
                        style={{ textAlign: "center" }}
                        ref={locationInputRef}
                    />
                    <FontAwesomeIcon
                        icon={faLocationDot}
                        className="absolute right-3 ml-2 top-1/2 transform -translate-y-1/2 text-black cursor-pointer"
                    />
                </div>
                <Select
                    className="w-full md:flex-1"
                    options={categories}
                    value={selectedCategory}
                    onChange={setSelectedCategory}
                    placeholder="Select a category"
                    isClearable
                    styles={{
                        control: (provided) => ({
                            ...provided,
                            borderRadius: "12px",
                            padding: "2px 0", // Adjust this value as needed
                        }),
                    }}
                />
                <button className="btn-primary w-full md:w-auto py-3 rounded-full px-4 focus:outline-none mt-4 md:mt-0">
                    <FontAwesomeIcon icon={faSearch} />
                </button>
            </div> */}
                <div className="pt-4">
                    {/*<ListingSearch />*/}
                    <Search />
                </div>

                {/* Price Range Slider */}
                <div className="flex flex-col lg:flex-row items-center gap-6 my-6">
                    <div
                        id="turnover_slider"
                        className="w-full border rounded-lg jakarta border-[#CBD5E1] space-y-2 px-6 py-4"
                    >
                        <label className="text-gray-700 font-semibold ">
                            Turnover Range
                        </label>
                        <div id="slider" className=" "></div>
                        <div className="row mt-3 ">
                            <div className="col-6 mt-1">
                                <span
                                    id="price_low"
                                    className="py-0 "
                                    name="min"
                                ></span>
                            </div>
                            <div className="col-6 mt-1 pr-0">
                                <span
                                    id="price_high"
                                    className="float-right py-0 "
                                    name="min"
                                ></span>
                            </div>
                        </div>
                    </div>

                    <div
                        id="amount_slider"
                        className="w-full jakarta   text-md border border-[#cbd5e1] rounded-lg space-y-2 px-6 py-4  mt-1"
                    >
                        <label className="text-gray-700 font-semibold mb-2">
                            Amount Range
                        </label>
                        <div id="slider2" className=""></div>
                        <div className="row mt-3 jakarta">
                            <div className="col-6 mt-1">
                                <span
                                    id="price_low2"
                                    className="py-0 text-sm "
                                    name="min"
                                ></span>
                            </div>
                            <div className="col-6 mt-1 pr-0">
                                <span
                                    id="price_high2"
                                    className="float-right py-0 text-sm "
                                    name="min"
                                ></span>
                            </div>
                        </div>
                    </div>
                </div>
                {/* Price Range Slider */}

                {/*<PriceRangeFilter />
        <PriceRangeFilter />*/}

                <h1 className=" text-gray-700 text-2xl mb-2   font-semibold ">
                    <b>{count} Results Found</b>
                    {/* <button className="permission-granted-button">
                  {" "}
                  Allow location{" "}
              </button> */}
                </h1>
                <div className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] lg:gap-8 gap-4 items-start">
                    {/* Cards Section */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 px-1 sm:px-4 lg:px-0">
                        {currentCards.length === 0 ? (
                            <div className="space-y-4">
                                {/* Skeleton Loader for Cards */}
                                {[...Array(3)].map((_, index) => (
                                    <div
                                        key={index}
                                        className="border p-5 border-gray-200 shadow-sm bg-white rounded-2xl flex flex-col w-full max-w-[500px] sm:max-w-[600px] lg:max-w-[700px] mx-auto h-full animate-pulse"
                                    >
                                        {/* Skeleton Content */}
                                        <div className="bg-gray-200 w-full h-[200px] sm:h-[220px] lg:h-[250px] rounded-lg"></div>
                                        <div className="flex flex-col pt-4 justify-between flex-grow pb-4">
                                            {/* Additional Skeleton Elements */}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        ) : (
                            currentCards.map((row) => (
                                <Link
                                    to={`/listing/${btoa(btoa(row.id))}`}
                                    key={row.id}
                                >
                                    <div className="border p-5 border-gray-200 shadow-sm bg-white rounded-2xl flex flex-col w-full max-w-[500px] sm:max-w-[600px] lg:max-w-[700px] mx-auto h-full">
                                        <div className="w-full h-[180px] sm:h-[200px] lg:h-[250px]">
                                            <img
                                                src={"../../" + row.image}
                                                alt={row.name}
                                                className="w-full h-full object-cover rounded-lg"
                                            />
                                        </div>
                                        <div className="flex flex-col pt-4 justify-between flex-grow pb-4">
                                            <div className="flex flex-wrap gap-2 text-sm font-bold text-[#1E293B] mb-2">
                                                {(
                                                    row.tags || [
                                                        "example",
                                                        "dummy",
                                                    ]
                                                ).map((tag) => (
                                                    <span
                                                        key={tag}
                                                        className="text-[#1E293B] font-semibold"
                                                    >
                                                        #{tag}
                                                    </span>
                                                ))}
                                            </div>
                                            <p className="text-lg font-semibold text-[#1E293B] mb-2">
                                                {row.name}
                                            </p>
                                            <p className="text-sm text-[#1E293B] mb-2">
                                                {row.details ||
                                                    "Lorem ipsum dolor sit amet consectetur..."}
                                            </p>
                                            <p className="text-sm text-[#1E293B] mb-2">
                                                {row.category}
                                            </p>
                                            <div className="text-sm text-gray-600 flex flex-col gap-1 mb-2">
                                                <p className="flex items-center">
                                                    <FontAwesomeIcon
                                                        icon={faLocationDot}
                                                        className="mr-2"
                                                    />
                                                    {row.location}
                                                </p>
                                                <p className="flex items-center">
                                                    <FontAwesomeIcon
                                                        icon={faPhone}
                                                        className="mr-2"
                                                    />
                                                    contact:{" "}
                                                    {row.contact ||
                                                        "+1791205437"}
                                                </p>
                                            </div>
                                            <div className="text-sm text-green-600 mb-1">
                                                <p>
                                                    $
                                                    {row.investment_needed ||
                                                        ""}
                                                    <span className="text-[#1E293B]">
                                                        {" "}
                                                        / Amount Requested
                                                    </span>
                                                </p>
                                            </div>
                                            <div className="text-sm text-green-600">
                                                <p>
                                                    ${row.y_turnover || ""}
                                                    <span className="text-[#1E293B]">
                                                        {" "}
                                                        / Yearly Turnover
                                                    </span>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </Link>
                            ))
                        )}
                    </div>

                    {/* Map Section */}
                    <div className="h-[500px] lg:h-auto rounded-lg flex items-center justify-center">
                        <div
                            className="map_style w-full h-full"
                            style={{
                                borderRadius: "16px",
                                overflow: "hidden",
                            }}
                        >
                            <div
                                id="map"
                                style={{
                                    height: "100%",
                                    width: "100%",
                                    borderRadius: "16px",
                                }}
                            ></div>
                        </div>
                    </div>
                    {/* Pagination - Positioned outside of the cards div */}
                    <div className="flex justify-start ml-6 mt-4">
                        <CardsPagination
                            currentPage={currentPage}
                            totalPages={totalPages}
                            onPageChange={handlePageChange}
                        />
                    </div>
                </div>
            </div>
        </>
    );
};

export default ListingResults;
